version: '3'
services:
  server:
    build:
      context: ./
      dockerfile: ./nebula/NebulaServer.Dockerfile
    image: nebula/server
    ports:
      - "9190:9190"
    # We're using this for performance profiling NET_ADMIN, SYS_ADMIN
    # remove it in final production.
    cap_add:
      - ALL
  envoy:
    build:
      context: ./
      dockerfile: ./http/envoy.Dockerfile
    image: nebula/envoy
    ports:
      - "8080:8080"
    links:
      - server
  web:
    build:
      context: ./
      dockerfile: ./http/web.Dockerfile
    image: nebula/web
    ports:
      - "8088:8088"
    links:
      - envoy