version: '3'
services:
  node:
    build:
      context: ./
      dockerfile: ./node/NodeServer.Dockerfile
    image: nebula/node
    ports:
      - "9199:9199"
    cap_add:
      - ALL
  server:
    build:
      context: ./
      dockerfile: ./server/NebulaServer.Dockerfile
    image: nebula/server
    ports:
      - "9190:9190"
    # We're using this for performance profiling NET_ADMIN, SYS_ADMIN
    # remove it in final production.
    cap_add:
      - ALL
    links:
      - node
  envoy:
    build:
      context: ./
      dockerfile: ./http/envoy.Dockerfile
    image: nebula/envoy
    ports:
      - "8080:8080"
    links:
      - server
  web:
    build:
      context: ./
      dockerfile: ./http/web.Dockerfile
      args:
        SERVER: http://dev-shawncao:8080
    image: nebula/web
    ports:
      - "8088:8088"
    links:
      - envoy
